### ISSUE TITLE
Ubuntu 16.04 and 16.10 needs review 

### ISSUE THREAD

**Issue by gOOvER** [servisys/ispconfig_setup#148]
In Ubuntu 16.04 and 16.10 are a lot of missing installations. 

Both scripts need to be reviewed

**Comment by Dracozny** [comment]
Problems I found so far:
firewall rules are not set up, First, you have to `ufw allow 8080`, then you have to go into server settings in Ispconfig to enable the firewall rules otherwise many things will not work.

There is no Letsencrypt cert installed for Ispconfig webroot instead it uses a self-signed cert. But it does use Letsencrypt for client sites.

Jailkit is broken due to bad permissions on /var/www

no webmail application installed. I wound up using RoundCube, but that is a hot mess and is still not completely integrated.

**Comment by servisys** [comment]
Maybe all fixed now, missing some php packages :)

Need to test.
