### ISSUE TITLE
Ubuntu 16.04 MUST be reviewed

### ISSUE THREAD

**Issue by gOOvER** [servisys/ispconfig_setup#174]
The Install Script have a lot of missing steps. The whole installscript should be reviewed

**Comment by mpathy** [comment]
Thats true..
I got no question for the ISPconfig admin user, but could reset it in the database.
Also at one point the output on console was broken and all the text was written in one line, overwriting itself each time..
The logfile was also unreadable because of the ANSI Codes for coloring, I think..

**Comment by servisys** [comment]
Tested yesterday. ISPconfig default user and pass are admin/admin and they works.
