### ISSUE TITLE
Support for Debian Strech 

### ISSUE THREAD

**Issue by brightcolor** [servisys/ispconfig_setup#193]
Any Plans to add Support for the new Debian Strech?

**Comment by servisys** [comment]
When ispconfig will support it officially :)

Inviato da Nexus 6

Il 18 giu 2017 7:04 PM, "brightcolor" <notifications@github.com> ha scritto:

Any Plans to add Support for the new Debian Strech?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/servisys/ispconfig_setup/issues/193>, or mute the thread

**Comment by OliverTempel** [comment]
ISPConfig 3.1.4  released with stretch support :)

**Comment by servisys** [comment]
I'll work on it soon :)

**Comment by servisys** [comment]
Added.
